export const vehiclesData = [
  {
    id: "veh001",
    title: "Toyota Camry",
    category: "Car",
    brand: "Toyota",
    model: "Camry",
    transmission: "Automatic",
    fuelType: "Petrol",
    seatingCapacity: 5,
    mileage: "18 km/l",
    pricePerDay: 4500,
    features: ["AC", "GPS", "Bluetooth", "Airbags"],
    description:
      "A premium mid-size sedan perfect for long trips and city drives.",
    image: [
      "https://www.edmunds.com/assets/m/cs/blt95cf4db396c717b7/672bda61733622566a9c6cac/2024-toyota-camry-actf34.jpg",
    ],
  },
  {
    id: "veh002",
    title: "KTM Duke 390",
    category: "2-Wheeler",
    brand: "KTM",
    model: "Duke 390",
    transmission: "Manual",
    fuelType: "Petrol",
    seatingCapacity: 2,
    mileage: "25 km/l",
    pricePerDay: 2500,
    features: ["Bluetooth", "ABS"],
    description: "A powerful and sporty motorcycle built for thrill seekers.",
    image: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Ktm_duke_390.jpg/1200px-Ktm_duke_390.jpg",
    ],
  },
  {
    id: "veh003",
    title: "Honda Activa 6G",
    category: "2-Wheeler",
    brand: "Honda",
    model: "Activa 6G",
    transmission: "Automatic",
    fuelType: "Petrol",
    seatingCapacity: 2,
    mileage: "50 km/l",
    pricePerDay: 2000,
    features: ["USB Charger", "Silent Start"],
    description: "India's most trusted scooter, great for everyday use.",
    image: [
      "https://images.firstpost.com/wp-content/uploads/2020/02/Activa-6g-1280.jpg?im=FitAndFill=(596,336)",
    ],
  },
  {
    id: "veh004",
    title: "Suzuki Swift Dzire",
    category: "Car",
    brand: "Suzuki",
    model: "Swift Dzire",
    transmission: "Manual",
    fuelType: "Petrol",
    seatingCapacity: 5,
    mileage: "22 km/l",
    pricePerDay: 4000,
    features: ["AC", "GPS", "Power Steering"],
    description: "A stylish compact sedan with great mileage and comfort.",
    image: [
      "https://meromoto.com/_next/image?url=https%3A%2F%2Fs3.meromoto.com%2Fimages%2Fvehicles%2F875770de-1c9f-419a-92ef-9beb297f9a81%2F3e0d2a89-d927-43bc-bc66-fead807581c1.webp&w=3840&q=75",
      "https://media.licdn.com/dms/image/v2/C4E1BAQFburGlX8VBSA/company-background_10000/company-background_10000/0/1593693109319/cimage_cover?e=2147483647&v=beta&t=g_VbV3v7jxduBq83_0vCwBmrrjLCY9xFTWERSyIwv7k",
    ],
  },
  {
    id: "veh005",
    title: "Mahindra E-Rickshaw",
    category: "E-Rickshaw",
    brand: "Mahindra",
    model: "Treo",
    transmission: "Automatic",
    fuelType: "Electric",
    seatingCapacity: 4,
    mileage: "130 km/charge",
    pricePerDay: 1800,
    features: ["GPS", "Eco Mode"],
    description: "An eco-friendly rickshaw ideal for short city commutes.",
    image: [
      "https://truckcdn.cardekho.com/in/mahindra/treo-yaari/mahindra-treo-yaari-62610.jpg",
    ],
  },
  {
    id: "veh006",
    title: "Tata Ace",
    category: "Truck",
    brand: "Tata",
    model: "Ace",
    transmission: "Manual",
    fuelType: "Diesel",
    seatingCapacity: 2,
    mileage: "17 km/l",
    pricePerDay: 6000,
    features: ["Heavy Load", "GPS"],
    description:
      "A reliable mini-truck suitable for transporting goods and cargo.",
    image: [
      "https://www.tatamotors.com.np/sites/nepal/files/styles/webp/public/product/images/image%20%2873%29.png.webp?itok=Lmmrst_y",
    ],
  },
];
