export const vehiclesData = [
  {
    id: "veh001",
    title: "Toyota Camry",
    category: "Car",
    brand: "Toyota",
    model: "Camry",
    transmission: "Automatic",
    fuelType: "Petrol",
    seatingCapacity: 5,
    mileage: "18 km/l",
    pricePerDay: 4500,
    features: ["AC", "GPS", "Bluetooth", "Airbags"],
    description:
      "A premium mid-size sedan perfect for long trips and city drives.",
    image:
      "https://www.edmunds.com/assets/m/cs/blt95cf4db396c717b7/672bda61733622566a9c6cac/2024-toyota-camry-actf34.jpg",
  },
  {
    id: "veh002",
    title: "KTM Duke 390",
    category: "2-Wheeler",
    brand: "KTM",
    model: "Duke 390",
    transmission: "Manual",
    fuelType: "Petrol",
    seatingCapacity: 2,
    mileage: "25 km/l",
    pricePerDay: 2500,
    features: ["Bluetooth", "ABS"],
    description: "A powerful and sporty motorcycle built for thrill seekers.",
    image:
      "https://preview.redd.it/2023-ktm-duke-390-upgrade-suggestions-please-v0-9x2mqhvzwyqc1.jpeg?width=1080&crop=smart&auto=webp&s=bba6912b737a20bd622c7ad1f8afae94ada4aef8",
  },
  {
    id: "veh003",
    title: "Honda Activa 6G",
    category: "2-Wheeler",
    brand: "Honda",
    model: "Activa 6G",
    transmission: "Automatic",
    fuelType: "Petrol",
    seatingCapacity: 2,
    mileage: "50 km/l",
    pricePerDay: 2000,
    features: ["USB Charger", "Silent Start"],
    description: "India's most trusted scooter, great for everyday use.",
    image:
      "https://imgd.aeplcdn.com/1280x720/n/cw/ec/44686/activa-6g-right-front-three-quarter.jpeg",
  },
  {
    id: "veh004",
    title: "Suzuki Swift Dzire",
    category: "Car",
    brand: "Suzuki",
    model: "Swift Dzire",
    transmission: "Manual",
    fuelType: "Petrol",
    seatingCapacity: 5,
    mileage: "22 km/l",
    pricePerDay: 4000,
    features: ["AC", "GPS", "Power Steering"],
    description: "A stylish compact sedan with great mileage and comfort.",
    image:
      "https://i0.wp.com/bestsellingcarsblog.com/wp-content/uploads/2025/06/Maruti-Suzuki-DZire-India-May-2025.jpg?resize=600%2C398",
  },
  {
    id: "veh005",
    title: "Mahindra E-Rickshaw",
    category: "E-Rickshaw",
    brand: "Mahindra",
    model: "Treo",
    transmission: "Automatic",
    fuelType: "Electric",
    seatingCapacity: 4,
    mileage: "130 km/charge",
    pricePerDay: 1800,
    features: ["GPS", "Eco Mode"],
    description: "An eco-friendly rickshaw ideal for short city commutes.",
    image:
      "https://electrek.co/wp-content/uploads/sites/3/2024/03/mahindra-three-wheeler-trike.jpg?quality=82&strip=all&w=1600",
  },
  {
    id: "veh006",
    title: "Tata Ace",
    category: "Truck",
    brand: "Tata",
    model: "Ace",
    transmission: "Manual",
    fuelType: "Diesel",
    seatingCapacity: 2,
    mileage: "17 km/l",
    pricePerDay: 6000,
    features: ["Heavy Load", "GPS"],
    description:
      "A reliable mini-truck suitable for transporting goods and cargo.",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQshZJEFwEIAJTgsLFNVPFnAWfFGuP-PP0SA&s",
  },
];
